FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .

RUN chmod +x gradlew

COPY src src

EXPOSE 8080

ENV SPRING_DOCKER_COMPOSE_ENABLED=false

CMD ["./gradlew", "bootRun", "--no-daemon", "--continuous"]
